export const MIN_DESTINATIONS_PER_COUNTRY = 12;

export const COUNTRY_DESTINATION_SUGGESTIONS: Record<string, string[]> = {
    "Argentina": ["Buenos Aires", "Bariloche", "Mendoza", "Cordoba", "Salta", "Puerto Iguazu", "Mar del Plata", "Ushuaia", "El Calafate", "Rosario", "San Martin de los Andes", "Villa La Angostura", "Tigre", "La Plata"],
    "Australia": ["Sydney", "Melbourne", "Brisbane", "Gold Coast", "Cairns", "Adelaide", "Perth", "Hobart", "Canberra", "Darwin", "Noosa", "Byron Bay", "Port Douglas", "Sunshine Coast"],
    "Austria": ["Vienna", "Salzburg", "Innsbruck", "Graz", "Linz", "Hallstatt", "Klagenfurt", "Bregenz", "Zell am See", "St Anton am Arlberg", "Mayrhofen", "Kitzbuhel", "Melk", "Wachau"],
    "Belgium": ["Brussels", "Bruges", "Ghent", "Antwerp", "Leuven", "Mechelen", "Dinant", "Namur", "Ostend", "Ypres", "Liege", "Spa", "Durbuy", "Hasselt"],
    "Brazil": ["Rio de Janeiro", "Florianopolis", "Sao Paulo", "Salvador", "Foz do Iguacu", "Brasilia", "Curitiba", "Belo Horizonte", "Recife", "Fortaleza", "Natal", "Paraty", "Buzios", "Gramado"],
    "Canada": ["Vancouver", "Victoria", "Toronto", "Montreal", "Quebec City", "Ottawa", "Calgary", "Banff", "Whistler", "Niagara Falls", "Halifax", "Jasper", "Kelowna", "Prince Edward Island"],
    "Chile": ["Santiago", "Valparaiso", "Vina del Mar", "Puerto Varas", "San Pedro de Atacama", "La Serena", "Pucon", "Torres del Paine", "Puerto Natales", "Concepcion", "Chiloe", "Frutillar", "Punta Arenas", "Easter Island"],
    "Colombia": ["Cartagena", "Medellin", "Bogota", "Santa Marta", "San Andres", "Salento", "Villa de Leyva", "Guatape", "Cali", "Barranquilla", "Minca", "Manizales", "Pereira", "Armenia"],
    "Costa Rica": ["San Jose", "La Fortuna", "Monteverde", "Manuel Antonio", "Tamarindo", "Liberia", "Puerto Viejo de Talamanca", "Jaco", "Samara", "Nosara", "Uvita", "Tortuguero", "Arenal", "Dominical"],
    "Croatia": ["Dubrovnik", "Zagreb", "Split", "Zadar", "Rovinj", "Pula", "Sibenik", "Trogir", "Hvar", "Korcula", "Plitvice Lakes", "Makarska", "Opatija", "Cavtat"],
    "Czech Republic": ["Prague", "Cesky Krumlov", "Brno", "Karlovy Vary", "Kutna Hora", "Olomouc", "Pilsen", "Liberec", "Telc", "Ostrava", "Ceske Budejovice", "Mikulov", "Lednice", "Marianske Lazne"],
    "Denmark": ["Copenhagen", "Aarhus", "Billund", "Odense", "Aalborg", "Roskilde", "Skagen", "Esbjerg", "Helsingor", "Ribe", "Svendborg", "Bornholm", "Silkeborg", "Kolding"],
    "Ecuador": ["Quito", "Galapagos Islands", "Cuenca", "Guayaquil", "Banos", "Mindo", "Otavalo", "Montanita", "Salinas", "Loja", "Cotopaxi National Park", "Riobamba", "Tena", "Puerto Ayora"],
    "France": ["Paris", "Nice", "Lyon", "Bordeaux", "Strasbourg", "Annecy", "Montpellier", "Nantes", "Toulouse", "Marseille", "Avignon", "Colmar", "Biarritz", "Chamonix"],
    "Germany": ["Berlin", "Munich", "Hamburg", "Cologne", "Dresden", "Heidelberg", "Nuremberg", "Frankfurt", "Freiburg", "Stuttgart", "Leipzig", "Bremen", "Dusseldorf", "Rothenburg ob der Tauber"],
    "Hungary": ["Budapest", "Lake Balaton", "Eger", "Pecs", "Szeged", "Debrecen", "Sopron", "Gyor", "Szentendre", "Visegrad", "Keszthely", "Tihany", "Hortobagy", "Miskolc"],
    "Iceland": ["Reykjavik", "Akureyri", "Vik", "Husavik", "Selfoss", "Hofn", "Seydisfjordur", "Egilsstadir", "Stykkisholmur", "Isafjordur", "Keflavik", "Borgarnes", "Thingvellir National Park", "Golden Circle"],
    "Ireland": ["Dublin", "Galway", "Cork", "Killarney", "Limerick", "Kilkenny", "Dingle", "Waterford", "Sligo", "Westport", "Donegal", "Kinsale", "Doolin", "Wicklow"],
    "Italy": ["Rome", "Florence", "Venice", "Milan", "Bologna", "Naples", "Sorrento", "Amalfi Coast", "Sicily", "Sardinia", "Verona", "Pisa", "Turin", "Lucca", "Cinque Terre"],
    "Japan": ["Tokyo", "Kyoto", "Osaka", "Nara", "Okinawa", "Yokohama", "Hiroshima", "Hakone", "Sapporo", "Fukuoka", "Kanazawa", "Nagano", "Kobe", "Nikko"],
    "Mexico": ["Mexico City", "Cancun", "Playa del Carmen", "Tulum", "Puerto Vallarta", "San Miguel de Allende", "Oaxaca", "Merida", "Guadalajara", "Puebla", "Cozumel", "Los Cabos", "La Paz", "Mazatlan"],
    "Netherlands": ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Haarlem", "Leiden", "Delft", "Maastricht", "Eindhoven", "Groningen", "Giethoorn", "Arnhem", "Nijmegen", "Alkmaar"],
    "Norway": ["Oslo", "Bergen", "Tromso", "Stavanger", "Trondheim", "Alesund", "Kristiansand", "Lillehammer", "Geiranger", "Flam", "Bodo", "Svolvaer", "Fredrikstad", "Molde"],
    "Panama": ["Panama City", "Bocas del Toro", "Boquete", "San Blas Islands", "El Valle de Anton", "Pedasi", "Santa Catalina", "David", "Portobelo", "Contadora Island", "Taboga Island", "Volcan", "Gamboa", "Coronado"],
    "Peru": ["Lima", "Cusco", "Arequipa", "Machu Picchu", "Sacred Valley", "Puno", "Paracas", "Huacachina", "Trujillo", "Chiclayo", "Iquitos", "Huaraz", "Nazca", "Puerto Maldonado"],
    "Portugal": ["Lisbon", "Porto", "Algarve", "Madeira", "Azores", "Cascais", "Sintra", "Coimbra", "Evora", "Braga", "Aveiro", "Lagos", "Faro", "Obidos"],
    "Serbia": ["Belgrade", "Novi Sad", "Nis", "Subotica", "Zlatibor", "Kopaonik", "Tara National Park", "Vrnjacka Banja", "Sremski Karlovci", "Kragujevac", "Golubac", "Sokobanja", "Uzice", "Zrenjanin"],
    "Singapore": ["Singapore", "Sentosa Island", "Marina Bay", "Orchard Road", "Jurong", "Changi", "Katong", "Little India", "Chinatown Singapore", "Bugis", "Tiong Bahru", "Pulau Ubin", "Dempsey Hill", "East Coast Park"],
    "Spain": ["Barcelona", "Madrid", "Valencia", "Seville", "Malaga", "Granada", "San Sebastian", "Bilbao", "Mallorca", "Tenerife", "Las Palmas", "Telde", "Cordoba", "Alicante", "Girona"],
    "Sweden": ["Stockholm", "Gothenburg", "Malmo", "Uppsala", "Visby", "Kiruna", "Lund", "Helsingborg", "Vasteras", "Orebro", "Linkoping", "Karlstad", "Falun", "Kalmar"],
    "Switzerland": ["Zurich", "Lucerne", "Interlaken", "Geneva", "Basel", "Bern", "Lausanne", "Zermatt", "Lugano", "Montreux", "St Moritz", "Grindelwald", "Locarno", "Thun"],
    "Turkey": ["Istanbul", "Antalya", "Cappadocia", "Izmir", "Bodrum", "Fethiye", "Ankara", "Pamukkale", "Marmaris", "Kas", "Alanya", "Side", "Bursa", "Trabzon"],
    "United Kingdom": ["London", "Edinburgh", "Bath", "York", "Cambridge", "Oxford", "Cornwall", "Lake District", "Belfast", "Liverpool", "Manchester", "Brighton", "Cardiff", "Glasgow"],
    "United States": ["Orlando", "San Diego", "Washington DC", "New York City", "Boston", "Chicago", "San Francisco", "Seattle", "Portland", "Honolulu", "Maui", "Oahu", "Yellowstone National Park", "Grand Canyon National Park", "Yosemite National Park", "Anaheim", "San Antonio", "Austin", "Denver", "Charleston", "Savannah", "Asheville", "Myrtle Beach", "Hilton Head Island", "Outer Banks", "Key West", "Miami", "Tampa", "St Petersburg", "Scottsdale", "Sedona", "Monterey", "Santa Barbara", "Lake Tahoe"],
    "Vietnam": ["Ho Chi Minh City", "Hanoi", "Hoi An", "Da Nang", "Nha Trang", "Hue", "Sapa", "Ha Long Bay", "Phu Quoc", "Da Lat", "Can Tho", "Mui Ne", "Ninh Binh", "Con Dao"],
};
